import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import AppShell from "@/components/AppShell";
import ClientProviders from "@/components/ClientProviders";
import NotificationPermissionRequester from "@/components/NotificationPermissionRequester";
import GlobalMessengerNotificationListener from "@/components/GlobalMessengerNotificationListener";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "HAKO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ margin: 0, padding: 0 }}
      >
        <ClientProviders>
          <NotificationPermissionRequester />
          <GlobalMessengerNotificationListener />
          <AppShell>{children}</AppShell>
        </ClientProviders>
      </body>
    </html>
  );
}
