import MessengerClientWrapper from "@/components/MessengerClientWrapper";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Hộp thư • Chat",
  description: "Generated by create next app",
  icons: {
    icon: "/Images/instagram.png",
  },
  openGraph: {
    title: "Hộp thư • Chát",
    description: "Trò chuyện cùng bạn bè trên HAKO",
    url: "https://instagram-clone-seven-sable.vercel.app/messages",
    siteName: "HAKO",
    images: [
      {
        url: "/Images/instagram.png",
        width: 800,
        height: 600,
      },
    ],
    locale: "vi_VN",
    type: "website",
  },
};

export default function MessagesPage() {
  return (
    <div>
      <MessengerClientWrapper />
    </div>
  );
}
